#!/usr/bin/env python3
"""mkromh.py -- pack config.bin into the _bootrom[] C array format used by
fujinet-firmware/pico/intellivision/firmware/include/fujiconfigrom.h.

The array is the raw big-endian .bin bytes verbatim (no transformation):
fujiboot.c's RunFujiConfig() reads it back as
    cart.ROM[i] = _bootrom[(i*2)+1] | (_bootrom[i*2] << 8)
i.e. byte order is already big-endian-word-pair, exactly what as1600
already produces in a PiRTO/Intellicart .bin.

Usage: mkromh.py config.bin > config_rom.h
"""
import sys

def main():
    if len(sys.argv) != 2:
        print(f"usage: {sys.argv[0]} config.bin", file=sys.stderr)
        return 1

    with open(sys.argv[1], "rb") as f:
        data = f.read()

    print("/*")
    print("  Boot ROM for the RP2040 cartridge -- FujiNet CONFIG for Intellivision")
    print("  (source: ~/Workspace/fujinet-config/intv/), assembled to Intellicart")
    print("  BIN+CFG format and embedded here so the Intellivision boots straight")
    print("  into it: WiFi setup, host slots, directory browsing, boot a selected")
    print("  ROM. Generated by intv/mkromh.py -- do not hand-edit.")
    print()
    print("  Regenerate after editing the .bas sources:")
    print("    cd fujinet-config/intv && make rom.h")
    print("    cp config_rom.h /path/to/fujinet-firmware/pico/intellivision/firmware/include/fujiconfigrom.h")
    print("*/")
    print("#ifndef FUJICONFIGROM_H")
    print("#define FUJICONFIGROM_H")
    print()
    print(f"static const unsigned char _bootrom[{len(data)}] = {{")
    for i in range(0, len(data), 16):
        chunk = data[i:i + 16]
        print("  " + ", ".join(f"0x{b:02X}" for b in chunk) + ",")
    print("};")
    print()
    print("#endif /* FUJICONFIGROM_H */")
    return 0

if __name__ == "__main__":
    sys.exit(main())
