#!/bin/bash
if [[ -z "$1" || "$1" == "-h" ]]; then
  echo "Usage: $0 <platform>"
  echo "  Builds the specified platform using fujinet-lib-experimental."
  echo "  Example: $0 msdos"
  exit 0
fi
make FUJINET_LIB=https://github.com/FozzTexx/fujinet-lib-experimental.git PLATFORMS=$1 $1
