#!/usr/bin/env python3
"""mktiles.py -- a MARIA 320B tile set (maria.h's mt_tiles) from tile art.

128 tiles of 8 x 8 pixels, 2 bits each, as indirect two-byte characters:
8 pages of 256 bytes, page 7 the top pixel row (MARIA counts a zone's lines
down), tile t at bytes 2t and 2t+1 of each page. In a byte, pixel j of 4
takes its high bit from bit 7-j and its low bit from bit 3-j.

Sources, either or both (font.txt wins where both define a tile):

  font.txt   the NES CONFIG's format: "= c" or "= $hh [plane N]" headers,
             then up to 8 rows of '#' and '.'. '#' is --ink (plane 0) or
             --ink1 (plane 1); '.' is --paper. Undefined tiles are all paper.
  --chr F    NES CHR (16 bytes a tile, plane 0 then plane 1): pixel value =
             plane0 | plane1 << 1, tiles from --chr-at (default 0).

    mktiles.py [--ink 1] [--ink1 3] [--paper 2] [--chr F [--chr-at N]]
               [font.txt] out.s [--png sheet.png]
"""

import sys

TILES = 128


def parse_font(path, ink, ink1, paper, tiles):
    cur = None
    for lineno, raw in enumerate(open(path, encoding="ascii"), 1):
        line = raw.rstrip("\n")
        if line == "" or line == "#" or line.startswith("# "):
            cur = None
            continue
        if line.startswith("= "):
            words = line[2:].split()
            name = line[2:3] if len(line) == 3 else words[0]
            if len(name) == 1:
                code = ord(name)
            elif name.startswith("$"):
                code = int(name[1:], 16)
            else:
                sys.exit(f"{path}:{lineno}: bad tile name {name!r}")
            plane = int(words[2]) if len(words) == 3 and words[1] == "plane" else 0
            if not 0 <= code < TILES:
                sys.exit(f"{path}:{lineno}: tile ${code:02X} out of range")
            cur = tiles[code] = [[paper] * 8 for _ in range(8)]
            cur_ink = ink1 if plane else ink
            cur_row = 0
            continue
        if cur is None or len(line) > 8 or set(line) - set("#.") or cur_row == 8:
            sys.exit(f"{path}:{lineno}: bad glyph row {line!r}")
        for x, ch in enumerate(line):
            cur[cur_row][x] = cur_ink if ch == "#" else paper
        cur_row += 1


def parse_chr(path, at, tiles):
    data = open(path, "rb").read()
    for n in range(len(data) // 16):
        if at + n >= TILES:
            break
        t = data[n * 16:n * 16 + 16]
        tiles[at + n] = [[((t[y] >> (7 - x)) & 1) | (((t[8 + y] >> (7 - x)) & 1) << 1)
                          for x in range(8)] for y in range(8)]


def encode(px):
    """Eight pixel values -> the two 320B bytes."""
    out = []
    for half in (px[0:4], px[4:8]):
        b = 0
        for j, v in enumerate(half):
            b |= ((v >> 1) & 1) << (7 - j) | (v & 1) << (3 - j)
        out.append(b)
    return out


def build(tiles, paper):
    blank = [[paper] * 8 for _ in range(8)]
    pages = []
    for page in range(8):
        y = 7 - page
        row = []
        for t in range(TILES):
            row += encode(tiles.get(t, blank)[y])
        pages.append(row)
    return pages


def write_png(tiles, paper, path):
    from PIL import Image
    pal = [(0, 0, 0), (255, 255, 255), (40, 40, 160), (90, 200, 255)]
    img = Image.new("RGB", (128, 64))
    blank = [[paper] * 8 for _ in range(8)]
    for t in range(TILES):
        g = tiles.get(t, blank)
        for y in range(8):
            for x in range(8):
                img.putpixel(((t % 16) * 8 + x, (t // 16) * 8 + y), pal[g[y][x]])
    img.resize((512, 256), Image.NEAREST).save(path)


def main():
    args = sys.argv[1:]
    opts = {"--ink": 1, "--ink1": 3, "--paper": 2, "--chr-at": 0}
    chr_path = png = None
    rest = []
    while args:
        a = args.pop(0)
        if a in opts:
            opts[a] = int(args.pop(0), 0)
        elif a == "--chr":
            chr_path = args.pop(0)
        elif a == "--png":
            png = args.pop(0)
        else:
            rest.append(a)
    if not rest or len(rest) > 2:
        sys.exit(__doc__)
    out = rest[-1]
    tiles = {}
    if chr_path:
        parse_chr(chr_path, opts["--chr-at"], tiles)
    if len(rest) == 2:
        parse_font(rest[0], opts["--ink"], opts["--ink1"], opts["--paper"], tiles)
    pages = build(tiles, opts["--paper"])
    with open(out, "w", encoding="ascii") as f:
        f.write("; generated by mktiles.py -- do not edit\n\n")
        f.write("        .export _mt_tiles\n\n")
        f.write('        .segment "TILES"\n\n_mt_tiles:\n')
        for page, row in enumerate(pages):
            f.write("; pixel row %d\n" % (7 - page))
            for i in range(0, 256, 16):
                f.write("        .byte " + ",".join("$%02X" % b for b in row[i:i + 16]) + "\n")
    if png:
        write_png(tiles, opts["--paper"], png)


if __name__ == "__main__":
    main()
