#ifndef PMD_COLORS_H
#define PMD_COLORS_H

#include <conio.h>
#include "screen_util.h"

// Text colors and Fill patterns

#define BACKGROUND_COLOR	BLUE
//#define BACKGROUND_PATTERN	(PATTERN_SOLID | ACE_BLUE)
//#define BACKGROUND_PATTERN	(PATTERN_CHESSBOARD | ACE_BLUE)
#define BACKGROUND_PATTERN	(PATTERN_BLANK | ACE_BLUE)

#define LIST_COLOR			WHITE
#define LIST_PATTERN		ACE_BLUE
#define LIST_TITLE_COLOR	YELLOW
#define LIST_TITLE_PATTERN  PATTERN_BLANK
#define LIST_VBAR_COLOR		CYAN
#define LIST_VBAR_PATTERN	ACE_CYAN

#define BAR_PATTERN_ON  	(PATTERN_REVERSE | ACE_CYAN)
#define BAR_PATTERN_OFF     (PATTERN_REVERSE | ACE_WHITE)

#define EDITLINE_COLOR		GREEN
#define EDITLINE_PATTERN_ON	 (MASK_KEEP_BITMAP | ACE_GREEN)
#define EDITLINE_PATTERN_OFF (MASK_KEEP_BITMAP | ACE_WHITE)

#define CURSOR_COLOR		WHITE
#define CURSOR_PATTERN_ON   (MASK_KEEP_BITMAP | 0x3E3E | ACE_WHITE)
#define CURSOR_PATTERN_OFF  (MASK_KEEP_BITMAP | 0x3E3E | ACE_WHITE)

#define STATUSBAR_COLOR     WHITE
#define STATUSBAR_PATTERN   PATTERN_BLANK

#endif // PMD_COLORS_H