#!/usr/bin/env python3
"""mkromh.py -- pack a built Astrocade CONFIG image into a C array.

Vendored from fujinet-firmware/pico/astrocade/tools/mkromh.py. The cart
firmware's fuji_config_boot() runs astromap_plan/apply over _configrom[],
so this emits the 8192 image as raw bytes (this port serves the window
byte-for-byte -- unlike the Intellivision packer, which emits big-endian
word pairs). Copy the result over
fujinet-firmware/pico/astrocade/firmware/include/fujiconfigrom.h and rebuild
the cart firmware to bake it in.

Usage: mkromh.py image.bin > fujiconfigrom.h
"""

import sys

def main() -> int:
    if len(sys.argv) != 2:
        print(__doc__.strip(), file=sys.stderr)
        return 2
    with open(sys.argv[1], "rb") as f:
        img = f.read()
    print("// Generated by mkromh.py -- do not edit.")
    print("#pragma once")
    print(f"#define FUJI_CONFIGROM_SIZE {len(img)}")
    print(f"static const unsigned char _configrom[{len(img)}] = {{")
    for i in range(0, len(img), 12):
        row = ", ".join(f"0x{b:02x}" for b in img[i:i + 12])
        print(f"    {row},")
    print("};")
    return 0

if __name__ == "__main__":
    sys.exit(main())
