#!/usr/bin/env python3
"""mkfont.py -- turn font.txt into the tiles CONFIG loads at power-on.

Every tile CONFIG draws is one colour on transparent/black, so the data is
1bpp: eight row bytes per tile plus the colour index the loader spreads them
into (fujidisp.c expands each row over the four Mode 4 bitplanes). Tiles
0-127 are emitted -- the frame, cursor and sprite tiles below 32, then the
font with tile number = ASCII code, which is what the MAME harness's
smstext.lua reads back. Tiles not given are blank.

    mkfont.py font.txt build/font_data.c [--png sheet.png]

--png writes a contact sheet of all 128 tiles (4x scale) for checking the
drawing without running an emulator.
"""

import struct
import sys
import zlib

TILES = 128


def parse(path):
    tiles = {}
    colour = {}
    cur = None
    for lineno, raw in enumerate(open(path, encoding="ascii"), 1):
        line = raw.rstrip("\n")
        if line == "" or line == "#" or line.startswith("# "):
            cur = None
            continue
        if line.startswith("= "):
            words = line[2:].split()
            name = line[2:3] if len(line) == 3 else words[0]
            if len(name) == 1:
                code = ord(name)
            elif name.startswith("$"):
                code = int(name[1:], 16)
            else:
                sys.exit(f"{path}:{lineno}: bad tile name {name!r}")
            ci = 1
            if len(words) == 3 and words[1] == "colour":
                ci = int(words[2])
            elif len(name) > 1 and len(words) != 1:
                sys.exit(f"{path}:{lineno}: expected '= $hh [colour N]'")
            if not 0 < code < TILES or code in tiles:
                sys.exit(f"{path}:{lineno}: tile ${code:02X} out of range or repeated")
            if not 0 < ci < 16:
                sys.exit(f"{path}:{lineno}: colour {ci} out of range")
            cur = tiles[code] = []
            colour[code] = ci
            continue
        if cur is None or len(line) != 8 or set(line) - set("#.") or len(cur) == 8:
            sys.exit(f"{path}:{lineno}: bad glyph row {line!r}")
        cur.append(line)
    return tiles, colour


def row_byte(line):
    return sum(1 << (7 - x) for x, c in enumerate(line) if c == "#")


def emit_c(tiles, colour, out):
    rows = []
    for code in range(TILES):
        lines = tiles.get(code, [])
        lines = lines + ["........"] * (8 - len(lines))
        rows.append([row_byte(l) for l in lines])
    with open(out, "w", encoding="ascii") as f:
        f.write("/* GENERATED by tools/mkfont.py from font.txt -- do not edit. */\n\n")
        f.write("const unsigned char font_rows[%d] = {\n" % (TILES * 8))
        for code in range(TILES):
            label = chr(code) if 32 < code < 127 and chr(code) not in "\\*/" else "$%02X" % code
            f.write("    " + ", ".join("0x%02X" % b for b in rows[code]) + ",  /* %s */\n" % label)
        f.write("};\n\n")
        f.write("const unsigned char font_colour[%d] = {\n" % TILES)
        for base in range(0, TILES, 16):
            f.write("    " + ", ".join(str(colour.get(c, 1)) for c in range(base, base + 16)) + ",\n")
        f.write("};\n")


def emit_png(tiles, out, scale=4):
    w, h = 16 * 9 * scale, 8 * 9 * scale
    px = [[(40, 40, 40)] * w for _ in range(h)]
    for code in range(TILES):
        tx, ty = (code % 16) * 9 * scale, (code // 16) * 9 * scale
        lines = tiles.get(code, [])
        for y in range(8):
            for x in range(8):
                on = y < len(lines) and lines[y][x] == "#"
                rgb = (255, 255, 255) if on else (0, 0, 0)
                for dy in range(scale):
                    for dx in range(scale):
                        px[ty + y * scale + dy][tx + x * scale + dx] = rgb
    raw = b"".join(b"\0" + bytes(c for p in row for c in p) for row in px)

    def chunk(kind, data):
        body = kind + data
        return struct.pack(">I", len(data)) + body + struct.pack(">I", zlib.crc32(body))

    with open(out, "wb") as f:
        f.write(b"\x89PNG\r\n\x1a\n")
        f.write(chunk(b"IHDR", struct.pack(">IIBBBBB", w, h, 8, 2, 0, 0, 0)))
        f.write(chunk(b"IDAT", zlib.compress(raw, 9)))
        f.write(chunk(b"IEND", b""))


def main(argv):
    if len(argv) not in (3, 5) or (len(argv) == 5 and argv[3] != "--png"):
        sys.exit(__doc__)
    tiles, colour = parse(argv[1])
    emit_c(tiles, colour, argv[2])
    if len(argv) == 5:
        emit_png(tiles, argv[4])


if __name__ == "__main__":
    main(sys.argv)
