#!/usr/bin/env python3
"""mkfont.py -- turn font.txt into the CHR-ROM's background pattern table.

Emits a ca65 source with a CHARS segment exporting NESfont, which stands in
for cc65's own neschar.s (crt0 .forceimports the symbol; an object file wins
over the library). 256 tiles, 4K: $00-$7F from font.txt, $80-$FF their
reverse-video copies (plane 0 inverted), which is what cc65's revers() picks.

    mkfont.py font.txt build/font.s [--png sheet.png]
"""

import sys

TILES = 128


def parse(path):
    tiles = {}
    cur = None
    for lineno, raw in enumerate(open(path, encoding="ascii"), 1):
        line = raw.rstrip("\n")
        if line == "" or line == "#" or line.startswith("# "):
            cur = None
            continue
        if line.startswith("= "):
            words = line[2:].split()
            name = line[2:3] if len(line) == 3 else words[0]
            if len(name) == 1:
                code = ord(name)
            elif name.startswith("$"):
                code = int(name[1:], 16)
            else:
                sys.exit(f"{path}:{lineno}: bad tile name {name!r}")
            plane = 0
            if len(words) == 3 and words[1] == "plane":
                plane = int(words[2])
            if not 0 <= code < TILES or code in tiles or code in (0x0A, 0x0D):
                # $0A/$0D are conio's LF/CR: cputc would never draw them
                sys.exit(f"{path}:{lineno}: tile ${code:02X} unusable or repeated")
            cur = tiles[code] = {"plane": plane, "rows": []}
            continue
        if cur is None or len(line) > 8 or set(line) - set("#.") \
                or len(cur["rows"]) == 8:
            sys.exit(f"{path}:{lineno}: bad glyph row {line!r}")
        cur["rows"].append(int(line.ljust(8, ".").replace("#", "1")
                               .replace(".", "0"), 2))
    return tiles


def chr_bytes(tiles):
    out = bytearray()
    for code in range(TILES):
        t = tiles.get(code, {"plane": 0, "rows": []})
        rows = t["rows"] + [0] * (8 - len(t["rows"]))
        p0 = rows if t["plane"] == 0 else [0] * 8
        p1 = rows if t["plane"] == 1 else [0] * 8
        out += bytes(p0) + bytes(p1)
    for code in range(TILES):
        base = code * 16
        out += bytes(b ^ 0xFF for b in out[base:base + 8]) + out[base + 8:base + 16]
    return out


def write_png(data, path):
    from PIL import Image
    pal = [(0, 0, 0), (255, 255, 255), (60, 190, 255), (0, 0, 170)]
    img = Image.new("RGB", (128, 128))
    for t in range(256):
        for y in range(8):
            lo, hi = data[t * 16 + y], data[t * 16 + 8 + y]
            for x in range(8):
                c = ((lo >> (7 - x)) & 1) | (((hi >> (7 - x)) & 1) << 1)
                img.putpixel(((t % 16) * 8 + x, (t // 16) * 8 + y), pal[c])
    img.resize((512, 512), Image.NEAREST).save(path)


def main():
    args = sys.argv[1:]
    png = None
    if "--png" in args:
        i = args.index("--png")
        png = args[i + 1]
        del args[i:i + 2]
    if len(args) != 2:
        sys.exit(__doc__)
    data = chr_bytes(parse(args[0]))
    with open(args[1], "w", encoding="ascii") as f:
        f.write("; generated by tools/mkfont.py from font.txt -- do not edit\n\n")
        f.write("        .export NESfont\n\n")
        f.write('.segment "CHARS"\n\nNESfont:\n')
        for i in range(0, len(data), 16):
            f.write("        .byte " + ",".join(f"${b:02X}" for b in data[i:i + 16]) + "\n")
    if png:
        write_png(data, png)


if __name__ == "__main__":
    main()
